movement.right = "key:d"
movement.left = "key:a"
player.destroy = "mouse:left"
movement.back = "key:s"
movement.crouch = "key:left-shift"
movement.jump = "key:space"
player.fast_interaction = "key:x"
movement.sprint = "key:left-ctrl"
hud.inventory = "key:tab"
player.attack = "mouse:left"
player.build = "mouse:right"
player.noclip = "key:n"
player.drop = "key:q"
hud.chat = "key:t"
movement.forward = "key:w"
player.pick = "mouse:middle"
devtools.console = "key:grave-accent"
chunks.reload = "key:f5"
camera.mode = "key:f4"
movement.cheat = "key:r"
player.flight = "key:f"
camera.zoom = "key:c"
